In [1]:
using Laplacians
using ProfileView

In [2]:
include("../../src/linkedListStorage.jl")

moduloNext (generic function with 1 method)

In [3]:
a = chimera(5,1);
rho = 1;

In [4]:
l = llsInit(a, rho)

LinkedListStorage{Float64,Int64}([#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],20,20,[-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1],5,20)

In [5]:
for i in 1:5
    llsAdd(l, 1, (1.0, 3, 4));
end
llsAdd(l, 2, (1.0, 3, 4))
for i in 1:5
    llsAdd(l, 1, (1.0, 3, 4));
end

l.val

20-element Array{element{Float64,Int64},1}:
    element{Float64,Int64}(1.0,3,4,2) 
    element{Float64,Int64}(1.0,3,4,3) 
    element{Float64,Int64}(1.0,3,4,4) 
    element{Float64,Int64}(1.0,3,4,5) 
    element{Float64,Int64}(1.0,3,4,7) 
    element{Float64,Int64}(1.0,3,4,-1)
    element{Float64,Int64}(1.0,3,4,8) 
    element{Float64,Int64}(1.0,3,4,9) 
    element{Float64,Int64}(1.0,3,4,10)
    element{Float64,Int64}(1.0,3,4,11)
    element{Float64,Int64}(1.0,3,4,-1)
 #undef                               
 #undef                               
 #undef                               
 #undef                               
 #undef                               
 #undef                               
 #undef                               
 #undef                               
 #undef                               

In [23]:
l.start

5-element Array{Int64,1}:
 -1
  6
 -1
 -1
 -1

In [24]:
l.last

5-element Array{Int64,1}:
 -1
  4
 -1
 -1
 -1

In [8]:
auxVal = zeros(Float64, 5)
auxMult = zeros(Int64, 5)
llsPurge(l, 1, auxVal, auxMult)

1
2
3
4
5
7
8
9
10
11


(10.0,[10.0],30,[30],[4])

In [9]:
l.val

20-element Array{element{Float64,Int64},1}:
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(1.0,3,4,-1)   
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
 #undef                                  
 #undef                                  
 #undef                                  
 #undef                                  
 #undef                                  
 #undef                                  
 #undef                                  
 #undef                                  
 #undef                                  

In [32]:
llsAdd(l, 2, (1.0, 3, 4));
l.val

20-element Array{element{Float64,Int64},1}:
 element{Float64,Int64}(1.0,3,4,2) 
 element{Float64,Int64}(1.0,3,4,3) 
 element{Float64,Int64}(1.0,3,4,4) 
 element{Float64,Int64}(1.0,3,4,5) 
 element{Float64,Int64}(1.0,3,4,7) 
 element{Float64,Int64}(1.0,3,4,12)
 element{Float64,Int64}(1.0,3,4,8) 
 element{Float64,Int64}(1.0,3,4,9) 
 element{Float64,Int64}(1.0,3,4,10)
 element{Float64,Int64}(1.0,3,4,11)
 element{Float64,Int64}(1.0,3,4,12)
 element{Float64,Int64}(1.0,3,4,-1)
 element{Float64,Int64}(1.0,3,4,14)
 element{Float64,Int64}(1.0,3,4,15)
 element{Float64,Int64}(1.0,3,4,16)
 element{Float64,Int64}(1.0,3,4,17)
 element{Float64,Int64}(1.0,3,4,18)
 element{Float64,Int64}(1.0,3,4,19)
 element{Float64,Int64}(1.0,3,4,20)
 element{Float64,Int64}(1.0,3,4,1) 

In [34]:
l.left

12

In [35]:
l.right


10