In [1]:
using Laplacians
using ProfileView

In [2]:
include("../../src/linkedListStorage.jl")

moduloNext (generic function with 1 method)

In [3]:
a = chimera(5,1);
rho = 1;

In [4]:
l = llsInit(a, rho)

LinkedListStorage{Float64,Int64}([#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef,#undef],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],20,20,[-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1],5,20)

In [5]:
for i in 1:5
    llsAdd(l, 1, (1.0, 3, 4));
end
llsAdd(l, 2, (1.0, 3, 4))
for i in 1:5
    llsAdd(l, 1, (1.0, 3, 4));
end

l.val

20-element Array{element{Float64,Int64},1}:
    element{Float64,Int64}(1.0,3,4,2) 
    element{Float64,Int64}(1.0,3,4,3) 
    element{Float64,Int64}(1.0,3,4,4) 
    element{Float64,Int64}(1.0,3,4,5) 
    element{Float64,Int64}(1.0,3,4,7) 
    element{Float64,Int64}(1.0,3,4,-1)
    element{Float64,Int64}(1.0,3,4,8) 
    element{Float64,Int64}(1.0,3,4,9) 
    element{Float64,Int64}(1.0,3,4,10)
    element{Float64,Int64}(1.0,3,4,11)
    element{Float64,Int64}(1.0,3,4,-1)
 #undef                               
 #undef                               
 #undef                               
 #undef                               
 #undef                               
 #undef                               
 #undef                               
 #undef                               
 #undef                               

In [6]:
l.start

LoadError: LoadError: type LinkedListStorage has no field start
while loading In[6], in expression starting on line 1

In [7]:
l.last

5-element Array{Int64,1}:
 11
  6
 -1
 -1
 -1

In [8]:
auxVal = zeros(Float64, 5)
auxMult = zeros(Int64, 5)
@code_warntype llsPurge(l, 1, auxVal, auxMult)

Variables:
  lls::LinkedListStorage{Float64,Int64}
  pos::Int64
  auxVal::Array{Float64,1}
  auxMult::Array{Int64,1}
  multSum::Int64
  diag::Float64
  res::Array{Float64,1}
  mult::Array{Int64,1}
  ind::Array{Int64,1}
  i::Int64
  actualMult::Int64
  #65#neigh::Int64
  w::Float64
  e::Int64
  #64#neigh::Int64
  ####fy#7614#8376::Float64
  _var0::Int64

Body:
  begin  # /Users/serbanstan/git/Laplacians.jl/src/linkedListStorage.jl, line 79:
      NewvarNode(:res)
      NewvarNode(:mult)
      NewvarNode(:ind)
      multSum = 0 # /Users/serbanstan/git/Laplacians.jl/src/linkedListStorage.jl, line 80:
      diag = (Base.box)(Float64,(Base.sitofp)(Float64,0)) # /Users/serbanstan/git/Laplacians.jl/src/linkedListStorage.jl, line 82:
      i = (Base.arrayref)((top(getfield))(lls::LinkedListStorage{Float64,Int64},:first)::Array{Int64,1},pos::Int64)::Int64 # /Users/serbanstan/git/Laplacians.jl/src/linkedListStorage.jl, line 83:
      NewvarNode(symbol("#64#neigh"))
      NewvarNode(:w)
      New

In [9]:
l.val

20-element Array{element{Float64,Int64},1}:
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(1.0,3,4,-1)   
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
    element{Float64,Int64}(-1.0,-1,-1,-1)
 #undef                                  
 #undef                                  
 #undef                                  
 #undef                                  
 #undef                                  
 #undef                                  
 #undef                                  
 #undef                                  
 #undef                                  

In [32]:
llsAdd(l, 2, (1.0, 3, 4));
l.val

20-element Array{element{Float64,Int64},1}:
 element{Float64,Int64}(1.0,3,4,2) 
 element{Float64,Int64}(1.0,3,4,3) 
 element{Float64,Int64}(1.0,3,4,4) 
 element{Float64,Int64}(1.0,3,4,5) 
 element{Float64,Int64}(1.0,3,4,7) 
 element{Float64,Int64}(1.0,3,4,12)
 element{Float64,Int64}(1.0,3,4,8) 
 element{Float64,Int64}(1.0,3,4,9) 
 element{Float64,Int64}(1.0,3,4,10)
 element{Float64,Int64}(1.0,3,4,11)
 element{Float64,Int64}(1.0,3,4,12)
 element{Float64,Int64}(1.0,3,4,-1)
 element{Float64,Int64}(1.0,3,4,14)
 element{Float64,Int64}(1.0,3,4,15)
 element{Float64,Int64}(1.0,3,4,16)
 element{Float64,Int64}(1.0,3,4,17)
 element{Float64,Int64}(1.0,3,4,18)
 element{Float64,Int64}(1.0,3,4,19)
 element{Float64,Int64}(1.0,3,4,20)
 element{Float64,Int64}(1.0,3,4,1) 

In [34]:
l.left

12

In [35]:
l.right


10