In [1]:
workspace()

In [3]:
push!(LOAD_PATH,"../../Laplacians.jl/src")
using Laplacians
push!(LOAD_PATH,"..")
push!(LOAD_PATH,".")

8-element Array{ByteString,1}:
 "/usr/local/Cellar/julia/0.4.0/local/share/julia/site/v0.4"
 "/usr/local/Cellar/julia/0.4.0/share/julia/site/v0.4"      
 "../../Laplacians.jl/src"                                  
 ".."                                                       
 "."                                                        
 "../../Laplacians.jl/src"                                  
 ".."                                                       
 "."                                                        

In [4]:
include("../myGraphOps.jl")

badFlowGraph (generic function with 1 method)

In [5]:
A,s,t = badFlowGraph(3);

In [6]:
n = A.n

22

In [7]:
L = lap(A);

In [8]:
eigvals(full(L))'

1x22 Array{Float64,2}:
 6.78163e-16  0.414267  0.740525  1.0  …  4.82065  5.20207  8.22283  8.52142

In [9]:
include("basicSolver.jl")

tomatrix (generic function with 1 method)

In [10]:
_,_,LDL = basicSolver(A,zeros(n));

In [11]:
norm(full(L))

8.521416189906452

In [12]:
norm(full(LDL-L))

1.7763568394002505e-15

In [49]:
include("samplingSolver.jl")

tomatrix (generic function with 1 method)

In [ ]:
u,d,LDL = samplingSolver(A,zeros(n));

1  [(1.0,38219,2),(1.0,38219,5),(1.0,38219,7),(1.0,38219,12)]
2  [(1.0,38219,3),(1.3082498233862739e-5,1,7),(1.3082498233862739e-5,1,5),(1.3082498233862739e-5,1,7),(1.3082498233862739e-5,1,12),(1.3082498233862739e-5,1,7),(1.3082498233862739e-5,1,7),(1.3082498233862739e-5,1,12),(1.3082498233862739e-5,1,5),(1.3082498233862739e-5,1,12),(1.3082498233862739e-5,1,5),(1.3082498233862739e-5,1,7),(1.3082498233862739e-5,1,5),(1.3082498233862739e-5,1,7),(1.3082498233862739e-5,1,7),(1.3082498233862739e-5,1,7),(1.3082498233862739e-5,1,12),(1.3082498233862739e-5,1,12),(1.3082498233862739e-5,1,12),(1.3082498233862739e-5,1,12),(1.3082498233862739e-5,1,5),(1.3082498233862739e-5,1,12),(1.3082498233862739e-5,1,7),(1.3082498233862739e-5,1,12),(1.3082498233862739e-5,1,7),(1.3082498233862739e-5,1,5),(1.3082498233862739e-5,1,7),(1.3082498233862739e-5,1,5),(1.3082498233862739e-5,1,12),(1.3082498233862739e-5,1,5),(1.3082498233862739e-5,1,7),(1.3082498233862739e-5,1,12),(1.3082498233862739e-5,1,12),(1.308249823

In [43]:
norm(full(LDL-L))

0.9386714294356351

In [44]:
sort(eigvals(full(LDL-L)))

22-element Array{Float64,1}:
 -0.938671   
 -0.328868   
 -0.239979   
 -0.196145   
 -0.172191   
 -0.148069   
 -0.112276   
 -0.109865   
 -0.094553   
 -0.0858441  
 -0.0710494  
 -0.0250415  
 -0.00292359 
 -0.000442132
 -0.00012333 
  0.0        
  1.04949e-16
  6.9851e-5  
  0.000443274
  0.000609839
  0.000696215
  0.00127227 

In [45]:
find(abs(full(LDL-L)) .> 0.5)

1-element Array{Int64,1}:
 484

In [46]:
d

22-element Array{Float64,1}:
 4.0    
 1.75039
 1.42857
 6.30115
 1.55248
 1.19666
 1.35999
 1.0611 
 3.79393
 1.737  
 1.42436
 5.43296
 1.56409
 1.17714
 1.40509
 0.9382 
 1.65023
 3.0571 
 1.22151
 1.51115
 1.98117
 0.0    

In [47]:
u

22-element Array{Array{Tuple{Float64,Int64},1},1}:
 [(-0.25,2),(-0.25,5),(-0.25,7),(-0.25,12),(1.0,1)]                                                                                                                                                                                                                                                                                                                
 [(-0.5713025800476493,3),(-0.14375616610376693,12),(-0.14164847977532613,5),(-0.14329277407411029,7),(1.0,2)]                                                                                                                                                                                                                                                     
 [(-0.6999987789710979,4),(-0.1001428606318647,7),(-0.09975213069950888,5),(-0.10010622970070635,12),(1.0,3)]                                                                                                                                

In [48]:
u[16]

13-element Array{Tuple{Float64,Int64},1}:
 (-0.22248900378215286,22) 
 (-0.0724516259245983,17)  
 (-0.19817571987802357,18) 
 (-0.02093023768457975,15) 
 (-0.1963071900114559,20)  
 (-0.09012162236772522,21) 
 (-0.03228413011517621,7)  
 (-0.02924782361846129,13) 
 (-0.08116531708039271,19) 
 (-0.019109637415730105,5) 
 (-0.008153028667258503,8) 
 (-0.029564663456244495,12)
 (1.0,16)                  