In [9]:
zeros(10,2)

10×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [16]:
Array{Bool}(undef,20)

20-element Array{Bool,1}:
 false
 false
 false
 false
  true
 false
 false
 false
 false
 false
 false
  true
  true
 false
 false
 false
 false
  true
 false
 false

In [17]:
trues(20)

20-element BitArray{1}:
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true

In [18]:
!false

true

In [19]:
~false

true

In [6]:
using Printf

In [7]:
@printf("time (sec) this iter = %.1f\n",time())

time (sec) this iter = 1563998436.2


In [9]:
convert(Int64,1e3)

1000

In [10]:
targ = "1e3"

"1e3"

In [11]:
n = 0

try
    n = convert(Int64,Base.parse(Float64,targ))
catch e
    n = Base.parse(Int64,targ)
end

1000

In [12]:
convert(Int64,Base.parse(Float64,targ))

1000

In [14]:
n

1000

In [16]:
pwd()

"/Users/rjkyng/Dropbox/Repos/Laplacians.jl/devel"

In [17]:
1:10:n

1:10:991

In [19]:
collect(1:ceil(sqrt(n)):n)

32-element Array{Float64,1}:
   1.0
  33.0
  65.0
  97.0
 129.0
 161.0
 193.0
 225.0
 257.0
 289.0
 321.0
 353.0
 385.0
   ⋮  
 641.0
 673.0
 705.0
 737.0
 769.0
 801.0
 833.0
 865.0
 897.0
 929.0
 961.0
 993.0